# Generated by Django 3.0.8 on 2020-08-15 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_meal_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='recipe',
            new_name='meal_recipe',
        ),
    ]
