# Generated by Django 3.0.8 on 2020-07-18 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='quantity',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='units',
            field=models.CharField(blank=True, choices=[('tsp', 'teaspoon'), ('tbsp', 'tablespoon'), ('lb', 'pound'), ('g', 'gram'), ('cup', 'cup'), ('oz', 'fluid ounce'), ('gal', 'gallon'), ('quart', 'quart'), ('pint', 'pint'), ('mL', 'milliliter'), ('L', 'liter'), ('dash', 'dash'), ('pinch', 'pinch'), ('stick', 'stick'), ('N/A', 'Null')], max_length=5),
        ),
    ]
