# Generated by Django 3.0.8 on 2020-07-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20200718_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='recipe_pics'),
        ),
    ]
