# Generated by Django 3.0.8 on 2020-08-10 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20200805_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='text',
            field=models.TextField(blank=True, verbose_name='Instructions'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_name',
            field=models.CharField(max_length=100, verbose_name='Ingredient Name'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='units',
            field=models.CharField(blank=True, choices=[('tsp', 'teaspoon'), ('tbsp', 'tablespoon'), ('lb', 'pound'), ('g', 'gram'), ('cup', 'cup'), ('oz', 'fluid ounce'), ('gal', 'gallon'), ('quart', 'quart'), ('pint', 'pint'), ('mL', 'milliliter'), ('L', 'liter'), ('dash', 'dash'), ('pinch', 'pinch'), ('stick', 'stick')], max_length=5),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.CharField(max_length=30, verbose_name='Prep Time'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_name',
            field=models.CharField(max_length=200, verbose_name='Recipe Name'),
        ),
    ]
