# Generated by Django 3.0.8 on 2020-10-09 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20200809_2004'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='direction',
            name='unique_position',
        ),
    ]
