# Generated by Django 3.0.8 on 2020-10-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20201009_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='position',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
